version: "3.9"
services:
  hftintern:
    container_name: hftintern
    build: .
    environment:
      NODE_ENV: dev
    env_file:
      - .env
    ports:
      - 9229:9229
    command: ["npm", "run", "dev"]
