app = "hftintern"

kill_signal = "SIGINT"
kill_timeout = 5

[build]
  dockerfile = "Dockerfile"

# [deploy]
#   release_command = "sh /usr/src/app/scripts/release.sh"

[env]
  BOT_TOKEN = "$BOT_TOKEN"
  CLIENT_ID = "$CLIENT_ID"
  HALOFUNTIME_API_KEY = "$HALOFUNTIME_API_KEY"
  HALOFUNTIME_API_URL = "https://api.halofuntime.com"
  PRIMARY_REGION = "dfw"

[experimental]
  allowed_public_ports = []
  auto_rollback = true
