name: Continuous Integration (CI)
on:
  pull_request:
    branches:
      - main
  workflow_call:
jobs:
  format:
    name: Check Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Check formatting
        uses: pre-commit/action@v3.0.0
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v3
      - name: Run Test Script
        run: echo "This is where we'd run our tests... IF WE HAD ANY!"
